[crypto]
salt = 64 # lenght of pseudo-random salt byte slice
iterations = 120000 # number of password iterations (OWASP recommended to use 120000 for PBKDF2-HMAC-SHA512)

[jwt]
issuer = "BytePass" # The identity of the party who issued the token.
publicKey = "jwt.pub" # RSA Public Key
privateKey = "jwt.key" # RSA Private Key
expiresAccessToken = 10 # Access token expiration time in minutes.
expiresRefreshToken = 60 # Refresh token expiration time in minutes.

[api]
address = ":8080"
tls = false # enable TLS server
certFile = "server.pem" # TLS certificate file
keyFile = "server.key" # TLS key file
